#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
//#define ID_TEX_MISC 20
//#define ID_TEX_ENEMY1 30
#define ID_TEX_MAP 30
#define ID_TEX_MAINMAP 20
#define ID_TEX_ENEMIES1 40
#define ID_TEX_MISC3 50
#define ID_TEX_MISC 60
#define ID_TEX_GOAL 70
#define ID_TEX_MARIO3 80
#define ID_TEX_ENEMIES2 200


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_GROUND	6
#define OBJECT_TYPE_TREE	7
#define OBJECT_TYPE_CLOUD	8
#define OBJECT_TYPE_BOX	9
#define OBJECT_TYPE_PIPE 10
#define OBJECT_TYPE_REDGOOMBA 11
#define OBJECT_TYPE_REDPLANT 12
#define OBJECT_TYPE_GREENPLANT 13
#define OBJECT_TYPE_PARINHA 14
#define OBJECT_TYPE_BULLET 15
#define OBJECT_TYPE_TROOPA 16
#define OBJECT_TYPE_PARATROOPA 17
#define OBJECT_TYPE_QUESTIONBLOCK 18
#define OBJECT_TYPE_ECOIN 19
#define OBJECT_TYPE_MUSHROOM 20


#define OBJECT_TYPE_PORTAL	50

#define SCENE_WIDTH 2654


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_IDLE_CARRY_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 30)
#define ID_SPRITE_MARIO_BIG_IDLE_CARRY_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 40)

#define ID_SPRITE_MARIO_BIG_TRANS_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 50)
#define ID_SPRITE_MARIO_BIG_TRANS_RIGHT	(ID_SPRITE_MARIO_BIG_IDLE + 60)
#define ID_SPRITE_MARIO_MIDDLE_TRANS_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 70)
#define ID_SPRITE_MARIO_MIDDLE_TRANS_RIGHT	(ID_SPRITE_MARIO_BIG_IDLE + 80)
#define ID_SPRITE_MARIO_NOTHING (ID_SPRITE_MARIO_BIG_IDLE + 90)


#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)

#define ID_SPRITE_MARIO_BIG_WALKING_CARRY_LEFT1 (ID_SPRITE_MARIO_BIG_WALKING + 30)
#define ID_SPRITE_MARIO_BIG_WALKING_CARRY_LEFT2 (ID_SPRITE_MARIO_BIG_WALKING + 40)

#define ID_SPRITE_MARIO_BIG_WALKING_CARRY_RIGHT1 (ID_SPRITE_MARIO_BIG_WALKING + 50)
#define ID_SPRITE_MARIO_BIG_WALKING_CARRY_RIGHT2 (ID_SPRITE_MARIO_BIG_WALKING + 60)

#define ID_SPRITE_MARIO_BIG_KICKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 70)
#define ID_SPRITE_MARIO_BIG_KICKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 80)

#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_IDLE_CARRY_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 30)
#define ID_SPRITE_MARIO_SMALL_IDLE_CARRY_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 40)
#define ID_SPRITE_MARIO_SMALL_TRANS_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 50)
#define ID_SPRITE_MARIO_SMALL_TRANS_RIGHT	(ID_SPRITE_MARIO_SMALL_IDLE + 60)


#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_WALKING_CARRY_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 30)
#define ID_SPRITE_MARIO_SMALL_WALKING_CARRY_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 40)

#define ID_SPRITE_MARIO_SMALL_KICKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 50)
#define ID_SPRITE_MARIO_SMALL_KICKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 60)



#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 600)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#define ID_SPRITE_MARIO_MAX (ID_SPRITE_MARIO + 4000)
#define ID_SPRITE_MARIO_MAX_IDLE (ID_SPRITE_MARIO_MAX + 100)
#define ID_SPRITE_MARIO_MAX_IDLE_LEFT (ID_SPRITE_MARIO_MAX_IDLE + 10)
#define ID_SPRITE_MARIO_MAX_IDLE_RIGHT (ID_SPRITE_MARIO_MAX_IDLE + 20)

#define ID_SPRITE_MARIO_MAX_IDLE_CARRY_LEFT (ID_SPRITE_MARIO_MAX_IDLE + 30)
#define ID_SPRITE_MARIO_MAX_IDLE_CARRY_RIGHT (ID_SPRITE_MARIO_MAX_IDLE + 40)


#define ID_SPRITE_MARIO_MAX_WALKING (ID_SPRITE_MARIO_MAX + 200)
#define ID_SPRITE_MARIO_MAX_WALKING_LEFT1 (ID_SPRITE_MARIO_MAX_WALKING + 10)
#define ID_SPRITE_MARIO_MAX_WALKING_LEFT2 (ID_SPRITE_MARIO_MAX_WALKING + 20)
#define ID_SPRITE_MARIO_MAX_WALKING_RIGHT1 (ID_SPRITE_MARIO_MAX_WALKING + 30)
#define ID_SPRITE_MARIO_MAX_WALKING_RIGHT2 (ID_SPRITE_MARIO_MAX_WALKING + 40)



#define ID_SPRITE_MARIO_MAX_WALKING_CARRY_LEFT1 (ID_SPRITE_MARIO_MAX_WALKING + 50)
#define ID_SPRITE_MARIO_MAX_WALKING_CARRY_LEFT2 (ID_SPRITE_MARIO_MAX_WALKING + 60)

#define ID_SPRITE_MARIO_MAX_WALKING_CARRY_RIGHT1 (ID_SPRITE_MARIO_MAX_WALKING + 90)
#define ID_SPRITE_MARIO_MAX_WALKING_CARRY_RIGHT2 (ID_SPRITE_MARIO_MAX_WALKING + 95)

#define ID_SPRITE_MARIO_MAX_KICKING_LEFT (ID_SPRITE_MARIO_MAX_WALKING + 70)
#define ID_SPRITE_MARIO_MAX_KICKING_RIGHT (ID_SPRITE_MARIO_MAX_WALKING + 80)

#define ID_SPRITE_MARIO_MAX_RUNNING (ID_SPRITE_MARIO_MAX + 300)

#define ID_SPRITE_MARIO_MAX_RUNNING_LEFT1 (ID_SPRITE_MARIO_MAX_RUNNING + 10)
#define ID_SPRITE_MARIO_MAX_RUNNING_LEFT2 (ID_SPRITE_MARIO_MAX_RUNNING + 20)
#define ID_SPRITE_MARIO_MAX_RUNNING_LEFT3 (ID_SPRITE_MARIO_MAX_RUNNING + 30)

#define ID_SPRITE_MARIO_MAX_RUNNING_RIGHT1 (ID_SPRITE_MARIO_MAX_RUNNING + 40)
#define ID_SPRITE_MARIO_MAX_RUNNING_RIGHT2 (ID_SPRITE_MARIO_MAX_RUNNING + 50)
#define ID_SPRITE_MARIO_MAX_RUNNING_RIGHT3 (ID_SPRITE_MARIO_MAX_RUNNING + 60)

#define ID_SPRITE_MARIO_MAX_JUMP (ID_SPRITE_MARIO_MAX + 400)

#define ID_SPRITE_MARIO_MAX_JUMP_WALK (ID_SPRITE_MARIO_MAX_JUMP + 10)

#define ID_SPRITE_MARIO_MAX_JUMP_WALK_LEFT (ID_SPRITE_MARIO_MAX_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_MAX_JUMP_WALK + 6)

#define ID_SPRITE_MARIO_MAX_JUMP_RUN (ID_SPRITE_MARIO_MAX_JUMP + 20)

#define ID_SPRITE_MARIO_MAX_JUMP_RUN_LEFT (ID_SPRITE_MARIO_MAX_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_MAX_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_MAX_SIT (ID_SPRITE_MARIO_MAX + 500)
#define ID_SPRITE_MARIO_MAX_SIT_LEFT (ID_SPRITE_MARIO_MAX_SIT + 10)
#define ID_SPRITE_MARIO_MAX_SIT_RIGHT (ID_SPRITE_MARIO_MAX_SIT + 20)

#define ID_SPRITE_MARIO_MAX_BRACE (ID_SPRITE_MARIO_MAX + 600)
#define ID_SPRITE_MARIO_MAX_BRACE_LEFT (ID_SPRITE_MARIO_MAX_BRACE + 10)
#define ID_SPRITE_MARIO_MAX_BRACE_RIGHT (ID_SPRITE_MARIO_MAX_BRACE + 20)

#define ID_SPRITE_MARIO_MAX_TURN_AROUND (ID_SPRITE_MARIO_MAX + 700)
#define ID_SPRITE_MARIO_MAX_TURN_LEFT (ID_SPRITE_MARIO_MAX_TURN_AROUND + 10)
#define ID_SPRITE_MARIO_MAX_TURN_RIGHT (ID_SPRITE_MARIO_MAX_TURN_AROUND + 20)
#define ID_SPRITE_MARIO_MAX_IS_IN_FRONT_OF (ID_SPRITE_MARIO_MAX_TURN_AROUND + 30)
#define ID_SPRITE_MARIO_MAX_IS_BACK (ID_SPRITE_MARIO_MAX_TURN_AROUND + 40)


#pragma endregion 

#define ID_SPRITE_BRICK 20000
#define ID_SPRITE_BRICK1 20001
#define ID_SPRITE_BRICK2 20002
#define ID_SPRITE_BRICK3 20003
#define ID_SPRITE_BRICK4 20004
#define ID_SPRITE_BRICK5 20005
#define ID_SPRITE_EFFECT_BRICK 20006
#define ID_SPRITE_BUTTON1 20007
#define ID_SPRITE_BUTTON2 20008
#define ID_SPRITE_BUTTON_AFTER_USE 20009
#define ID_SPRITE_POINT_TYPE1 20010
#define ID_SPRITE_POINT_TYPE2 20011
#define ID_SPRITE_POINT_TYPE10 20012
#define ID_SPRITE_1UP 20013
#define ID_SPRITE_BOXWHITE 20014
#define ID_SPRITE_RED_MUSHROOM 20015
#define ID_SPRITE_FLOWER 20016
#define ID_SPRITE_STAR 20017
#define ID_SPRITE_MUSH_EFFECT1 20018
#define ID_SPRITE_MUSH_EFFECT2 20019


#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)
#define ID_SPRITE_GOOMBA_OUT_GAME 30001


#define ID_SPRITE_COIN 40000
#define ID_SPRITE_COIN1 (ID_SPRITE_COIN + 1)
#define ID_SPRITE_COIN2 (ID_SPRITE_COIN + 2)
#define ID_SPRITE_COIN3 (ID_SPRITE_COIN + 3)
#define ID_SPRITE_COIN4 (ID_SPRITE_COIN + 4)
#define ID_SPRITE_COIN5 (ID_SPRITE_COIN + 5)
#define ID_SPRITE_ECOIN1 (ID_SPRITE_COIN + 6)
#define ID_SPRITE_ECOIN2 (ID_SPRITE_COIN + 7)
#define ID_SPRITE_ECOIN3 (ID_SPRITE_COIN + 8)
#define ID_SPRITE_ECOIN4 (ID_SPRITE_COIN + 9)
#define ID_SPRITE_MUSHROOMRED (ID_SPRITE_COIN + 10)
#define ID_SPRITE_MUSHROOMGREEN (ID_SPRITE_COIN + 13)
#define ID_SPRITE_LEAF_LEFT (ID_SPRITE_COIN + 11)
#define ID_SPRITE_LEAF_RIGHT (ID_SPRITE_COIN + 12)


#define ID_SPRITE_REDGOOMBA_WALK2_1 40100
#define ID_SPRITE_REDGOOMBA_WALK2_2 40200
#define ID_SPRITE_REDGOOMBA_WALK1_1 40300
#define ID_SPRITE_REDGOOMBA_WALK1_2	40400
#define ID_SPRITE_REDGOOMBA_DIE1 40500
#define ID_SPRITE_REDGOOMBA_FLY2_1 40600
#define ID_SPRITE_REDGOOMBA_FLY2_2 40700
#define ID_SPRITE_REDGOOMBA_OUT_GAME 40101

#define ID_SPRITE_REDPLANT_LEFTTOP 41100
#define ID_SPRITE_REDPLANT_RIGHTTOP 41200
#define ID_SPRITE_REDPLANT_LEFTBOTTOM 41300
#define ID_SPRITE_REDPLANT_RIGHTBOTTOM 41400

#define ID_SPRITE_GREENPLANT_LEFTTOP 41500
#define ID_SPRITE_GREENPLANT_RIGHTTOP 41600
#define ID_SPRITE_GREENPLANT_LEFTBOTTOM 41700
#define ID_SPRITE_GREENPLANT_RIGHTBOTTOM 41800

#define ID_SPRITE_PARINHA_OPEN 42100
#define ID_SPRITE_PARINHA_CLOSE 42200

#define ID_SPRITE_BULLET1 42300
#define ID_SPRITE_BULLET2 42400
#define ID_SPRITE_BULLET3 42500
#define ID_SPRITE_BULLET4 42600


#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)
#define ID_SPRITE_QUESBLOCK1 50101
#define ID_SPRITE_QUESBLOCK2 50201
#define ID_SPRITE_QUESBLOCK3 50301
#define ID_SPRITE_QUESBLOCK4 50401
#define ID_SPRITE_NO_QUESBLOCK 50501



#define ID_SPRITE_GROUND1 60000
#define ID_SPRITE_GROUND2 61000
#define ID_SPRITE_GROUND3 (ID_SPRITE_GROUND1 + 2000)
#define ID_SPRITE_GROUND4 (ID_SPRITE_GROUND1 + 3000)
#define ID_SPRITE_GROUND5 (ID_SPRITE_GROUND1 + 4000)



#define ID_SPRITE_GROUND1_1 60500
#define ID_SPRITE_GROUND1_2 61500
#define ID_SPRITE_GROUND1_3 62500
#define ID_SPRITE_GROUND1_4 63500
#define ID_SPRITE_GROUND1_5 64500
#define ID_SPRITE_QUESTION1 65500
#define ID_SPRITE_QUESTION2 66500
#define ID_SPRITE_BLUEBRICK 60001
#define ID_SPRITE_GROUP_BLUEBRICK 60002
#define ID_SPRITE_GROUND_BIG (ID_SPRITE_GROUND+5000)

#define ID_SPRITE_TREE1 66000
#define ID_SPRITE_TREE2 (ID_SPRITE_TREE1 + 1000)
#define ID_SPRITE_TREE3 (ID_SPRITE_TREE1 + 2000)
#define ID_SPRITE_TREE4 (ID_SPRITE_TREE1 + 3000)
#define ID_SPRITE_TREE5 (ID_SPRITE_TREE1 + 4000)
#define ID_SPRITE_TransTREE1 (ID_SPRITE_TREE1 + 501)
#define ID_SPRITE_TransTREE2 (ID_SPRITE_TREE2 + 502)
#define ID_SPRITE_BLACKBACKGROUND (ID_SPRITE_TREE3 + 500)
#define ID_SPRITE_BLACKBACKGROUND1 (ID_SPRITE_TREE1 + 200)
#define ID_SPRITE_BLACKBACKGROUND2 (ID_SPRITE_TREE1 + 212)

#define ID_SPRITE_BUSH 69500
#define ID_SPRITE_CLOUD1 71000
#define ID_SPRITE_CLOUD2 (ID_SPRITE_CLOUD1 + 1000)
#define ID_SPRITE_CLOUD3 (ID_SPRITE_CLOUD1 + 2000)

#define ID_SPRITE_BOX1 75000
#define ID_SPRITE_BOX2 (ID_SPRITE_BOX1 + 100)
#define ID_SPRITE_BOX3 (ID_SPRITE_BOX1 + 200)
#define ID_SPRITE_BOX4 (ID_SPRITE_BOX1 + 300)
#define ID_SPRITE_BOX5 (ID_SPRITE_BOX1 + 400)
#define ID_SPRITE_BOX6 (ID_SPRITE_BOX1 + 500)
#define ID_SPRITE_BOX7 (ID_SPRITE_BOX1 + 600)
#define ID_SPRITE_BOX8 (ID_SPRITE_BOX1 + 700)
#define ID_SPRITE_BOX9 (ID_SPRITE_BOX1 + 800)
#define ID_SPRITE_BOX10 (ID_SPRITE_BOX1 + 900)
#define ID_SPRITE_BOX11 (ID_SPRITE_BOX1 + 1000)
#define ID_SPRITE_BOX12 (ID_SPRITE_BOX1 + 1100)

#define ID_SPRITE_PIPE1 77000
#define ID_SPRITE_PIPE2 (ID_SPRITE_PIPE1 + 100)
#define ID_SPRITE_PIPE3 (ID_SPRITE_PIPE1 + 200)
#define ID_SPRITE_PIPE4 (ID_SPRITE_PIPE1 + 300)
#define ID_SPRITE_PIPE5 (ID_SPRITE_PIPE1 + 400)
#define ID_SPRITE_PIPE6 (ID_SPRITE_PIPE1 + 500)
#define ID_SPRITE_BLACKPIPE (ID_SPRITE_PIPE1 + 600)

#define ID_SPRITE_KOOPA_WALKING_LEFT1 80000
#define ID_SPRITE_KOOPA_WALKING_LEFT2 80010
#define ID_SPRITE_KOOPA_WALKING_RIGHT1 80020
#define ID_SPRITE_KOOPA_WALKING_RIGHT2 80030

#define ID_SPRITE_KOOPA_DIE3L 80040
#define ID_SPRITE_KOOPA_DIE2L 80041
#define ID_SPRITE_KOOPA_DIE1L 80042

#define ID_SPRITE_KOOPA_DIE3R 80043
#define ID_SPRITE_KOOPA_DIE2R 80044
#define ID_SPRITE_KOOPA_DIE1R 80045

#define ID_SPRITE_KOOPA_OUTGAME 80046

#define ID_SPRITE_TROOPA_WALKING_LEFT1 80001
#define ID_SPRITE_TROOPA_WALKING_LEFT2 80002
#define ID_SPRITE_TROOPA_WALKING_RIGHT1 80003
#define ID_SPRITE_TROOPA_WALKING_RIGHT2 80004
#define ID_SPRITE_TROOPA_DIE3L  80005
#define ID_SPRITE_TROOPA_DIE2L  80006
#define ID_SPRITE_TROOPA_DIE1L  80007
#define ID_SPRITE_TROOPA_DIE3R  80017
#define ID_SPRITE_TROOPA_DIE2R  80018
#define ID_SPRITE_TROOPA_DIE1R  80019
#define ID_SPRITE_TROOPA_FLIP_DIE 80008



#define ID_SPRITE_PARATROOPA_WALKING_LEFT1 80011
#define ID_SPRITE_PARATROOPA_WALKING_LEFT2 80012
#define ID_SPRITE_PARATROOPA_WALKING_LEFT3 80013
#define ID_SPRITE_PARATROOPA_WALKING_RIGHT1 80014
#define ID_SPRITE_PARATROOPA_WALKING_RIGHT2 80015
#define ID_SPRITE_PARATROOPA_WALKING_RIGHT3 80016