#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
//#define ID_TEX_MISC 20
//#define ID_TEX_ENEMY1 30
#define ID_TEX_MAP 30
#define ID_TEX_MAINMAP 20
#define ID_TEX_ENEMIES1 40


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_GROUND	6
#define OBJECT_TYPE_TREE	7
#define OBJECT_TYPE_CLOUD	8
#define OBJECT_TYPE_BOX	9
#define OBJECT_TYPE_PIPE 10


#define OBJECT_TYPE_PORTAL	50

#define SCENE_WIDTH 2654


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000
#define ID_SPRITE_COIN1 (ID_SPRITE_COIN + 1)
#define ID_SPRITE_COIN2 (ID_SPRITE_COIN + 2)
#define ID_SPRITE_COIN3 (ID_SPRITE_COIN + 3)
#define ID_SPRITE_COIN4 (ID_SPRITE_COIN + 4)
#define ID_SPRITE_COIN5 (ID_SPRITE_COIN + 5)



#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_SPRITE_GROUND1 60000
#define ID_SPRITE_GROUND2 61000
#define ID_SPRITE_GROUND3 (ID_SPRITE_GROUND1 + 2000)
#define ID_SPRITE_GROUND4 (ID_SPRITE_GROUND1 + 3000)
#define ID_SPRITE_GROUND5 (ID_SPRITE_GROUND1 + 4000)
#define ID_SPRITE_GROUND1_1 60500
#define ID_SPRITE_GROUND1_2 61500
#define ID_SPRITE_GROUND1_3 62500
#define ID_SPRITE_GROUND1_4 63500
#define ID_SPRITE_GROUND1_5 64500
#define ID_SPRITE_QUESTION1 65500
#define ID_SPRITE_QUESTION2 66500
#define ID_SPRITE_BLUEBRICK 60001
#define ID_SPRITE_GROUP_BLUEBRICK 60002
#define ID_SPRITE_GROUND_BIG (ID_SPRITE_GROUND+5000)

#define ID_SPRITE_TREE1 66000
#define ID_SPRITE_TREE2 (ID_SPRITE_TREE1 + 1000)
#define ID_SPRITE_TREE3 (ID_SPRITE_TREE1 + 2000)
#define ID_SPRITE_TREE4 (ID_SPRITE_TREE1 + 3000)
#define ID_SPRITE_TREE5 (ID_SPRITE_TREE1 + 4000)
#define ID_SPRITE_TransTREE1 (ID_SPRITE_TREE1 + 500)
#define ID_SPRITE_TransTREE2 (ID_SPRITE_TREE2 + 500)
#define ID_SPRITE_BLACKBACKGROUND (ID_SPRITE_TREE3 + 500)
#define ID_SPRITE_BUSH 69500

#define ID_SPRITE_CLOUD1 71000
#define ID_SPRITE_CLOUD2 (ID_SPRITE_CLOUD1 + 1000)
#define ID_SPRITE_CLOUD3 (ID_SPRITE_CLOUD1 + 2000)

#define ID_SPRITE_BOX1 75000
#define ID_SPRITE_BOX2 (ID_SPRITE_BOX1 + 100)
#define ID_SPRITE_BOX3 (ID_SPRITE_BOX1 + 200)
#define ID_SPRITE_BOX4 (ID_SPRITE_BOX1 + 300)
#define ID_SPRITE_BOX5 (ID_SPRITE_BOX1 + 400)
#define ID_SPRITE_BOX6 (ID_SPRITE_BOX1 + 500)
#define ID_SPRITE_BOX7 (ID_SPRITE_BOX1 + 600)
#define ID_SPRITE_BOX8 (ID_SPRITE_BOX1 + 700)
#define ID_SPRITE_BOX9 (ID_SPRITE_BOX1 + 800)
#define ID_SPRITE_BOX10 (ID_SPRITE_BOX1 + 900)
#define ID_SPRITE_BOX11 (ID_SPRITE_BOX1 + 1000)
#define ID_SPRITE_BOX12 (ID_SPRITE_BOX1 + 1100)

#define ID_SPRITE_PIPE1 77000
#define ID_SPRITE_PIPE2 (ID_SPRITE_PIPE1 + 100)
#define ID_SPRITE_PIPE3 (ID_SPRITE_PIPE1 + 200)
#define ID_SPRITE_PIPE4 (ID_SPRITE_PIPE1 + 300)
#define ID_SPRITE_PIPE5 (ID_SPRITE_PIPE1 + 400)
#define ID_SPRITE_PIPE6 (ID_SPRITE_PIPE1 + 500)
#define ID_SPRITE_BLACKPIPE (ID_SPRITE_PIPE1 + 600)

#define ID_SPRITE_KOOPA_WALKING_LEFT1 80000
#define ID_SPRITE_KOOPA_WALKING_LEFT2 80010
#define ID_SPRITE_KOOPA_WALKING_RIGHT1 80020
#define ID_SPRITE_KOOPA_WALKING_RIGHT2 80030

#define ID_SPRITE_KOOPA_DIE 80040